version: '3'
# 볼륨생성 위치: \\wsl.localhost\docker-desktop-data\mnt\wslg\distro\data\docker\volumes\security-guides_mysql_data\_data
volumes:
  mysql_data:
      driver: local

services:
  mysql:
      image: mysql:8.0.23
      volumes:
        - mysql_data:/var/lib/mysql
      ports:
        - 3309:3306
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:23.0.3
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - 8180:8080
      depends_on:
        - mysql
      command: start-dev
#http://localhost:8180/admin