x-logging: &logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  mysql:
      image: mysql:8.0.23
      ports:
        - 3309:3306
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
      command: # 명령어 실행
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      volumes:
        - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
  keycloak:
      image: quay.io/keycloak/keycloak:23.0.0
      command: ["start-dev", "--import-realm"]
      environment:
        KC_DB: mysql
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KC_DB_URL: "jdbc:mysql://mysql:3306/keycloak"
        KC_METRICS_ENABLED: true
        KC_LOG_LEVEL: info
        KC_REALM_NAME: security-guide
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      volumes:
        - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro
      logging: *logging
      ports:
        - 8180:8080
      depends_on:
        - mysql
        -
#http://localhost:8180/admin