### realms에 해당하는 유저 카운트 조회
GET {{keycloak-domain}}/admin/realms/security-guide/users/count
authorization: Bearer {{access_token}}

### 유저 목록 조회
GET {{keycloak-domain}}/admin/realms/security-guide/users
authorization: Bearer {{access_token}}

### 유저 삭제
DELETE {{keycloak-domain}}/admin/realms/security-guide/users/6cd17963-85f6-4735-8428-6e41e39955e1/consents
authorization: Bearer {{access_token}}

### 유저 수정
PUT {{keycloak-domain}}/admin/realms/security-guide/users/6cd17963-85f6-4735-8428-6e41e39955e1
authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "bb@b.com",
  "firstName": "홍",
  "lastName": "길동",
  "email": "bb@b.com"
}

### 유저 비밀번호 수정
PUT {{keycloak-domain}}/admin/realms/security-guide/users/6cd17963-85f6-4735-8428-6e41e39955e1/reset-password
authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "type": "password",
  "value": "1234",
  "temporary": false
}

### 사용자 이메일 검증
PUT {{keycloak-domain}}/admin/realms/security-guide/users/e480796b-ae48-4a33-81e5-d081a9ed464d/send-verify-email
authorization: Bearer {{access_token}}
Content-Type: application/json

### 사용자 생성
POST {{keycloak-domain}}/admin/realms/security-guide/users
authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "campion123@naver.com",
  "firstName": "Kim",
  "lastName": "Ricky",
  "email": "campion123@naver.com",
  "enabled": true,
  "emailVerified": true,
  "credentials": [
    {
      "type": "password",
      "value": "1234",
      "temporary": false
    }
  ]
}

### 사용자 권한 부여 가능 목록
GET {{keycloak-domain}}/admin/realms/security-guide/users/e480796b-ae48-4a33-81e5-d081a9ed464d/role-mappings/realm/available
authorization: Bearer {{access_token}}


### 사용자 권한 부여
POST {{keycloak-domain}}/admin/realms/security-guide/users/e480796b-ae48-4a33-81e5-d081a9ed464d/role-mappings/realm
authorization: Bearer {{access_token}}
Content-Type: application/json

[
  {
    "id": "cd44c035-107a-4238-9b46-0f33b333861c",
    "name": "USER"
  }
]

### 사용자 권한 삭제
DELETE {{keycloak-domain}}/admin/realms/security-guide/users/e480796b-ae48-4a33-81e5-d081a9ed464d/role-mappings/realm
authorization: Bearer {{access_token}}
Content-Type: application/json

[
  {
    "id": "cd44c035-107a-4238-9b46-0f33b333861c",
    "name": "USER"
  }
]


### Client 목록 조회
GET {{keycloak-domain}}/admin/realms/security-guide/clients
authorization: Bearer {{access_token}}