##################################################################
GET {{resource-domain}}/myCard?id=1
authorization: Bearer {{access_token}}

##################################################################
GET {{resource-domain}}/myAccount?id=1
authorization: Bearer {{access_token}}

##################################################################
GET {{resource-domain}}/myLoans?id=1
authorization: Bearer {{access_token}}

##################################################################
POST {{resource-domain}}/contact?id=1
authorization: Bearer {{access_token}}
Content-Type: application/json

[
  {
    "contactId": "contactId_c8f7c5fb49b3",
    "contactName": "contactName_596ac4bf03cb",
    "contactEmail": "contactEmail_af2eb915b2c0",
    "subject": "subject_076b602fa86d",
    "message": "message_5ad872a08b1a",
    "createDt": "2023-12-17"
  }
]
##################################################################
GET {{resource-domain}}/myBalance?id=1
authorization: Bearer {{access_token}}

### 회원가입
POST {{resource-domain}}/auth/signup
Content-Type: application/json

{
  "email": "c@cc.com",
  "password": "1234",
  "userRole": "USER",
  "firstName": "홍",
  "lastName": "길동"
}

### 로그인
POST {{resource-domain}}/auth/signin
Content-Type: application/json

{
  "email": "c@cc.com",
  "password": "1234"
}

> {%
    client.global.set("access_token", response.body.access_token)
%}